language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
  - '4'
  - '10'
branches:
  only:
    - 'master'
    - /^greenkeeper.*$/
  # except:
  #   - /^v\d+\.\d+\.\d+$/

before_install:
- npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - npm run verify

after_script: greenkeeper-lockfile-upload

after_success:
  - npm install coveralls && npm run coveralls
  - npm install -g travis-deploy-once@4
  - travis-deploy-once "npm run semantic-release"
